ips_list.yml
update-ips script fails when no ssh key is setup for auth on the system. Using https would be better.
=> Changed github access protocol in ip_list.yml

rtl/tb/dbg_pkg.sv, rtl/tb/jtag_pkg.sv, rtl/tb/pulp_tap_pkg.sv, rtl/tb/src_files.yml, rtl/tb/tb_pulp.sv
This patch re-enables loading binaries over the pulp tap, which is currently much faster than using the system bus access method of the debug module. `USE_PULP_BUS_ACCESS ` controls this behaviour and is enabled by default.
Furthermore some tasks were renamed to reflect the current capabilities more closely. All stuff related to the pulp tap is now called pulp_tap* instead of dbg_*.
The workaround of setting the reset pad with force/release is removed.
=> Reenable pulp tap

rtl/tb/jtag_pkg.sv
This was probably not valid SystemVerilog anyway.
Some simulators choke on this statement.
=> Fix indexing into packed struct in tb

sim/Makefile
Normally we don't use this target since running programs and calling
vsim is handled by the sdk. This fixes the case where one still wants to
manually open vsim.
=> Fix sim targets

rtl/tb/tb_pulp.sv
Sometimes we want to directly load a stimuli file from a compiled
program without using the pulp-sdk directly.
Pass `+stimuli=path_to_stimuli_file` to the simulator to specify such a
stimuli file.
=> Allow user to specify path to stimuli file

generate-scripts, sim/Makefile.incisive, sim/ncompile/build.mk
In general it suffices to call `make -f Makefile.incisive sim-sc` to
compile, elaborate and run a simulation. Consider using setting
`XRUN=+stim=path_to_stimuli_file` to load a specific program. There is no
pulp-sdk support yet.
The targets *-sc (sim-sc, build-sc) are doing a direct compilation and
elaboration of all required files (see `src_ips_files.f` and
`src_rtl_files.f`) at once, while *-r (sim-r, build-r, lib-r) are targets
that provide a library plus link flow our questasim build. As of now it
is not clear which one is superior, though the first one would allow us
to do multi-core simulations but this is not yet working.
Thus:
Prefer to use sim-sc/build-sc over the other build commands.
=> Add build and simulate flow for xcelium/ncsim

README.md, fpga/pulpissimo-genesys2/rtl/xilinx_pulpissimo.v, fpga/pulpissimo-nexys_video/rtl/xilinx_pulpissimo.v, fpga/pulpissimo-zcu104/rtl/xilinx_pulpissimo.v, rtl/pulpissimo/pulpissimo.sv
This PR performs the switch from Zero-riscy to Ibex. It updates
- the README.md: explain how to select Ibex instead of RI5CY,
- the top-level FPGA/RTL files: update the core selection comments
- and the version of the `pulp-soc` IP: select a version that is compatible with Ibex.
The default core configuration is still RI5CY. How to switch to Ibex is explained in the README.md.
This PR is based on pulp-platform/pulpissimo#72 and pulp-platform/pulp_soc#8. Once these PRs have been merged, I will do a rebase of this one and ask you to review it.
=> Switch from Zero-riscy to Ibex

rtl/includes/periph_bus_defines.sv, rtl/pulpissimo/safe_domain.sv
In reference to: #78 
Fixed errors:
- `periph_bus_defines.sv`: [double semicolon](https://github.com/MarekPikula/quartus-sv-gotchas/blob/master/Intel%20Quartus%20SystemVerilog%20gotchas.md#double-semicolon)
- `rtl/pulpissimo/safe_domain.sv`: [unnamed loop generate](https://github.com/MarekPikula/quartus-sv-gotchas/blob/master/Intel%20Quartus%20SystemVerilog%20gotchas.md#274-loop-generate-constructs-3)
=> Small fixes for Quartus compatibility

rtl/tb/tb_pulp.sv
Use `-gENTRY_POINT=your_boot_address`
This is typically set when the default boot address does not match the
elf entry point. This a bit hacky.
=> Allow setting entry point before simulation

fpga/pulpissimo-genesys2/fpga-settings.mk, fpga/pulpissimo-genesys2/ips/xilinx_slow_clk_mngr/tcl/run.tcl, fpga/pulpissimo-genesys2/rtl/fpga_slow_clk_gen.sv, fpga/pulpissimo-nexys_video/fpga-settings.mk, fpga/pulpissimo-nexys_video/ips/xilinx_slow_clk_mngr/tcl/run.tcl, fpga/pulpissimo-nexys_video/rtl/fpga_slow_clk_gen.sv, fpga/pulpissimo-zcu104/fpga-settings.mk, fpga/pulpissimo-zcu104/ips/xilinx_slow_clk_mngr/tcl/run.tcl, fpga/pulpissimo-zcu104/rtl/fpga_slow_clk_gen.sv
The pulp-sdk expects the slow clock to be 32kHZ. However, the MMCM/PLL resources on
the Xilinx FPGA do not support such low frequencies. We therefore generate an
intermediate clock (8 MHz) and slow it down with a clock divider using the
dedicated BUFCGE clock gating cells in conjunction with a counter.
=> Add clock divider in slow_clk_gen to generate 32kHz slow clock

generate-scripts, update-ips
* Add parameters that can be passed to generate-scripts and update-ips
--rt-dpi defines USE_DPI which in turn enables DPI emulation for
peripherals
--verbose prints more information about what is happening
* Changes are transparent, meaning previous behavior is not altered when
running these scripts
=> Provide option to build PULPissimo with DPI emulation for periph

fpga/pulpissimo-zedboard/rtl/xilinx_pulpissimo.v
All other implementations have this module enabled and
rudimentary tests show that it works just fine.
=> Enable FPU on Zedboard

.gitlab-ci.yml, ips_list.yml, sim/waves/core.tcl, update-tests, update-tests-gitlab
* Disable deprecated tests in `rt-tests`
* Disable simplified runtime tests (we have to carefully enabled these)
* Fix `ml_tests` (mlHom, mlFir, seizure)
=> Various fixes

fpga/pulpissimo-genesys2/constraints/genesys2.xdc, fpga/pulpissimo-nexys/constraints/nexys4.xdc, fpga/pulpissimo-nexys/constraints/nexys4DDR.xdc, fpga/pulpissimo-nexys_video/constraints/nexys_video.xdc, fpga/pulpissimo-zcu102/constraints/zcu102.xdc, fpga/pulpissimo-zcu104/constraints/zcu104.xdc, fpga/pulpissimo-zedboard/constraints/zedboard.xdc
The nets were renamed in b8c1a75a of the pulp_soc repository
without changing them here.
=> Fix net paths in constraints

.gitlab-ci.yml, fpga/pulpissimo-genesys2/constraints/genesys2.xdc, fpga/pulpissimo-genesys2/rtl/pulp_clock_gating_xilinx.sv, fpga/pulpissimo-nexys/constraints/nexys4.xdc, fpga/pulpissimo-nexys/constraints/nexys4DDR.xdc, fpga/pulpissimo-nexys/rtl/pulp_clock_gating_xilinx.sv, fpga/pulpissimo-nexys_video/constraints/nexys_video.xdc, fpga/pulpissimo-nexys_video/rtl/pulp_clock_gating_xilinx.sv, fpga/pulpissimo-zcu102/constraints/zcu102.xdc, fpga/pulpissimo-zcu102/rtl/pulp_clock_gating_xilinx.sv, fpga/pulpissimo-zcu104/constraints/zcu104.xdc, fpga/pulpissimo-zcu104/rtl/pulp_clock_gating_xilinx.sv, fpga/pulpissimo-zedboard/constraints/zedboard.xdc, fpga/pulpissimo-zedboard/fpga-settings.mk, fpga/pulpissimo-zedboard/rtl/pulp_clock_gating_xilinx.sv
- Add proper XDC constraints for all FPGA ports for all clock domain crossings
- Add a functional implementation of the functional clock gating cells in FPGA port
- Decrease default frequency on Zedboard to meet timing contraints with enabled FPU
- Add additional  Gitlab CI targets for all supported FPGA ports
=> Fix fpga timing

rtl/pulpissimo/soc_domain.sv
A recent change to pulp_soc (https://github.com/pulp-platform/pulp_soc/commit/f58645dca3cbb03a9fe1146c81cac53fb000bf5e) changed the default parameter of the Zfinx feature parameter of the RI5CY core. This commit overrides this new parameter to remain compatible with PULPissimos software infrastructure that assumes the presence of dedicated Floating Point registers.
=> Override new Zfinx parameter of pulp_soc

README.md, setup/vsim.sh
This small fix helps the script run correctly in ZSH environments.
`BASH_SOURCE[0]` is returned as empty in ZSH
=> setup/vsim.sh BASH_SOURCE for ZSH, add links to WOSH presentation

fpga/pulpissimo-zedboard/constraints/zedboard.xdc
AFAICT these create the following unnecessary critical warnings. Should be benign otherwise?
set_false_path:No valid object(s) found for '-from [get_ports pad_jtag_trst]'
set_max_delay:No valid object(s) found for '-from [get_ports pad_jtag_trst]'
This port is not exposed to the outside (similar to zcu102, zcu104, nexys (non-video)). Only the genesys2 and nexys-video ports expose this pin to the outside. Only the latter have similar constraints - the former do not mention `pad_jtag_trst` in their `.xdc`.
=> Zedboard: remove timing constraints for constant JTAG signal

fpga/pulpissimo-genesys2/rtl/fpga_clk_gen.sv, fpga/pulpissimo-nexys/rtl/fpga_clk_gen.sv, fpga/pulpissimo-nexys_video/rtl/fpga_clk_gen.sv, fpga/pulpissimo-zcu102/rtl/fpga_clk_gen.sv, fpga/pulpissimo-zcu104/rtl/fpga_clk_gen.sv, fpga/pulpissimo-zedboard/rtl/fpga_clk_gen.sv
From #203
>pulp-freertos was hanging when accessing the dummy FLLs. apb_fll_if expects a 4 cycle handshake: assert req, assert ack, >deassert req, deassert ack. The dummy (FPGA) FLL simply asserted ack all the time, which means the state machine hung in >phase 2.
>I have tested the fix on nexysA7-100T. The RTL looks identical on all of the platforms (might be preferable to have a Xilinx >directory that all Xilinx boards referred to) so I replaced all of them. The test consists of using gdb to observe that multiple reads >of the FLL registers don't hang. The actual application, hello_world_pmsis, does not function correctly which suggests there is >some other issue to be resolved.
=> corrected ack seq

.gitignore, Bender.local, Bender.yml, Makefile, README.md, setup/vsim.sh, sim/Makefile, update-ips
Add `Bender.yml` for bender support, add `Bender.local` for overrides, add Makefile compatibility with bender (set envvar `BENDER` to use `checkout`, `build`, `clean`)
=> Add Bender support

rtl/tb/SimJTAG.sv, rtl/tb/remote_bitbang/sim_jtag.c, rtl/tb/tb_pulp.sv
* Needs a PORT parameter
* sim_jtag.c should abort when provided bad arguments
=> tb: Fix SimJTAG instantiation

Bender.yml
Removed two files in the Bender file list since they are symlinks to the IPApprox ips directory. They should already be compiled as part of the tbtools dependency specification in Bender.yml.
=> Fix Bender file list

rtl/tb/tb_pulp.sv
Weirdly enough it works withouth this change, so it went through testing. Reverse it anyway.
=> tb: Reverse FAST_DEBUG_PRELOAD not driving bootsel

Bender.yml, sim/tcl_files/config/vsim.tcl
When cloning this from scratch and building with bender, I encountered a few minor issues building and running code, fixed here.
Also, I forgot to align `ips_list.yml`, fixed here. There are version conflicts present when using IPApproX, as the `fpnew` dependency has an `ips_list.yml` calling an older version of `common_cells`, and `register_interface` has an `ips_list.yml` calling an older version of `axi` ([being fixed](https://github.com/pulp-platform/pulp_soc/pull/53)).
=> Fix bender build & execution errors, align ips_list to bender

README.md
Add documentation for the workaround in gvsoc that enables the build under recent GCC version.
This pull request is dependent on pulp-platform/gvsoc#15 and together fixes the fatal build error described in pulp-platform/pulp-sdk#102.
=> Added documentation of workaround for GCC 11.1.0

rtl/tb/remote_bitbang/remote_bitbang.c, rtl/tb/remote_bitbang/remote_bitbang.h
This pull request fixes the linking of the bitbang library under modern GCC version where the multiple definitions of the global state results in the following error:
```bash
#> gcc (Gentoo Hardened 10.3.0 p1) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#> make all
cc -MT remote_bitbang.o -MMD -MP -MF ./.d/remote_bitbang.Td -std=gnu11 -fno-strict-aliasing -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-function -Wno-missing-braces -O2 -g -march=native -DENABLE_LOGGING -DNDEBUG -fPIC -I./  \
-c  remote_bitbang.c -o remote_bitbang.o …
```
=> Fixed linkage in remote_bitbang library

Bender.yml, Makefile
- Update bender to v0.24.0 to incorporate new bender features - requires fix due to changed `export_include_dir` handling
- Bump `pulp_soc` to v3.2.0 to fix #313 and use only https links (no git@ links requiring an uploaded ssh key)
=> Bump bender

rtl/tb/remote_bitbang/sim_jtag.c, rtl/tb/remote_bitbang/sim_jtag.h
When compiling for Verilator, you need to have the functions defined in the header file otherwise the function is not found at link time
=> fix sim_jtag for verilator

rtl/tb/jtag_pkg.sv
This fixes an issue where the load_L2 task would not load the last line
of stimulus when using the riscv-dbg module
=> Fix tb/jtag_pkg.sv load_L2 task
